site_name: Minigolf docs
nav:
    - Etusivu: index.md
    - Dokumentaatio:
      - Käyttöohje: kayttoohje
      - Arkkitehtuuri: arkkitehtuuri
      - Työaikakirjanpito: tyoaikakirjanpito
      - Vaatimusmäärittely: vaatimusmaarittely
      - Testausdokumentti: testaus
repo_url: https://github.com/makeri89/Ohjelmistotekniikka
theme: readthedocs
docs_dir: dokumentaatio
markdown_extensions:
  - sane_lists