name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: minigolf-game
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - uses: Gr1N/setup-poetry@v4
      - name: check poetry installation
        run: poetry --version
      - name: run tests
        run: poetry run invoke test